shinyorg/shiny

- src/Shiny.Locations/Distance.cs
- src/Shiny.Locations/GeofenceRegion.cs
- src/Shiny.Locations/Platforms/Android/GeofenceManagerImpl.cs
- src/Shiny.Locations/Position.cs
- tests/Shiny.Device.Tests.Shared/TestStartup.cs
- tests/Shiny.Tests/Locations/DistanceTests.cs
- tests/Shiny.Tests/Locations/GeofenceRegionTests.cs
- tests/Shiny.Tests/Locations/PositionTests.cs
1. Generally adds tests for Locations and fixes subtle bugs I noticed while skimming the project.
2. Fixes build error due to `ShinyStartup` rename
3. Changes a few places `await` was used on methods returning `Android.Gms.Tasks.Task` to use presumably equivalent methods returning .NET `Task`
- `distance.Equals(null)` NRE
- `geofenceRegion.Equals(null)` NRE
- `geofenceRegion.GetHashCode()` NRE for `null` identifier
- `position1.Equals(position2)` never `true`
- Added `Distance.FromMiles(double)`
- Should `FromMiles(int)` be marked `[Obsolete]`?
- All (most changes)
- Android (GMS async change)
None
Shiny.Tests.Locations are all passing. (Note: Shiny.Tests.Beacons and Shiny.Tests.Infrastructure fail for me locally.)
> Locations Cleanup

- src/Shiny.Locations/LocationLogCategory.cs
- src/Shiny.Locations/Platforms/Android/GeofenceProcessor.cs
- Check [`GeofencingEvent.HasError`](https://developers.google.com/android/reference/com/google/android/gms/location/GeofencingEvent.html#hasError()) and log `ErrorCode` if appropriate
- Log if `GeofenceEvent.RequestId` isn't found
- Log error from processing triggered geofence
- Fixes #37
None
- Android
None
It compiles.
> Check Geofence Error

- src/Shiny.Locations/Platforms/iOS/GeofenceManagerImpl.cs
- Updated Where lambda to compare the Region property of GeofenceCurrentStatus instead of the GeofenceCurrentStatus object itself
- Added Take to ensure the Observable returns a value instead of timing out
- RequestState for the iOS implementation was always throwing a TimeOutException
None
- iOS
None
Tested on iPhone with iOS 12.3.1. Set breakpoints to determine that GeofenceState was returning from RequestState after the updates.
> Fix RequestState for iOS timeout.

- src/Shiny.Core/Jobs/AbstractJobManager.cs
Jobs/Tasks now log Start/Success instead of Success twice.
- All
> Log: Differentiate Job/Task Start and Success

- src/Shiny.Core/Infrastructure/JsonNetSerializer.cs
Adds optional `JsonNetSerializer` constructor that accepts `JsonSerializerSettings`. Default constructor leaves `settings = null`, which aligns with internal behavior:
https://github.com/JamesNK/Newtonsoft.Json/blob/23be46f665887c9be03faf7864ae98890ca08246/Src/Newtonsoft.Json/JsonConvert.cs#L528-L531
Eliminates need to replicate the entire class to customize serialization.
New constructor; no breaking changes.
- All
None
> Accept JsonSerializerSettings

- src/Shiny.SpeechRecognition/Platforms/Android/SpeechRecognizerImpl.cs
Request for permission from user before recording audio for speech recognition.
The application would crash as permission was not granted. Following exception was caught 
```
**System.Exception:** 'Could not start speech recognizer - ERROR: InsufficientPermissions'
```
Change `RequestAccess()` method to async for Android implementation.
- Android
None
1.  Call `RequestAccess` method of `SpeechRecognizer`
2. It returns `AccessState.Available` as it only checked if `SpeechRecognizer` was available and RecordAudio permission was in manifest.
3. Added additional check to find if user has manually granted `RecordAudio` permission, otherwise request the user for it.
> fix : request permission from user for recording audio

- src/Shiny.Notifications/AndroidOptions.cs
- src/Shiny.Notifications/NotificationLogCategory.cs
- src/Shiny.Notifications/Platforms/Android/NotificationManager.cs
- src/Shiny.Notifications/Platforms/Android/PlatformExtensions.cs
- src/Shiny.Notifications/Platforms/Shared/NotificationModule.cs
Add `AndroidOptions` properties for:
- [`when`](https://developer.android.com/reference/android/app/Notification#when) ([`setWhen`](https://developer.android.com/reference/android/app/Notification.Builder.html#setWhen(long))/[`setShowWhen`](https://developer.android.com/reference/android/app/Notification.Builder.html#setShowWhen(boolean)))
- [`color`](https://developer.android.com/reference/android/app/Notification.html#color) ([`setColor`](https://developer.android.com/reference/android/app/Notification.Builder.html#setColor(int)))
- `Notifications.AndroidOptions` property changes:
- Add `bool? ShowWhen`, `DateTime? When`, and `static bool? DefaultShowWhen`
- Add `string? ColorResourceName` and `static string? DefaultColorResourceName`
- Mark `ChannelDescription` and …
> Android Notifications: When, ShowWhen, Color

- src/Shiny.Notifications/Platforms/Android/AndroidNotificationProcessor.cs
- src/Shiny.Notifications/Platforms/Uwp/NotificationBackgroundTaskProcessor.cs
Resolve `INotificationDelegate` manually and check for `null`, since it might not be registered. Similar to f39ea7ff5eff524a73cb9bb3667624e7f89aa276.
Implementation mirrors:
https://github.com/shinyorg/shiny/blob/af46ecfee901d8d5edc50ee3cee2a739f0ecef99/src/Shiny.Notifications/Platforms/Android/NotificationBroadcastReceiver.cs#L26-L28
Or it could be refactored to use `SafeResolveAndExecute()`:
https://github.com/shinyorg/shiny/blob/692df1d45d40bd170843dff89abf053640d2766a/src/Shiny.Notifications/Platforms/Android/NotificationManager.cs#L166
And for completeness, iOS uses `Lazy`:
https://github.com/shinyorg/shiny/blob/f39ea7ff5eff524a73cb9bb3667624e7f89aa276/src/Shiny.Notifications/Platforms/iOS/ShinyNotificationDelegate.cs#L10 https://github.com/shinyorg/shiny/blob/f39ea7ff5eff524a73cb9bb3 …
> [Android] Fix INotificationDelegate Not Registered

- input/docs/gettingstarted.md
Updated the startup guide for UWP.
When you use `EntryPoint="Shiny.Support.Uwp.ShinyBackgroundTask"`, then there will be a Validation error in the manifest.
None
None
- UWP
None
> Fix outdated startup guide for UWP

- src/Shiny.Beacons/readme.txt
Add in readme.txt documentation the Android 10+ prerequisite for Beacon Monitoring (background detection) as SDK 29 is needing ACCESS_BACKGROUND_LOCATION
I couldn't add it to the AssemblyInfo.cs as the project is targeting Android 9 (and the references isn't accessible on it).
Also as this new permissions isn't needed for all cases (Only for Monitoring).
Beacon monitoring wasn't working on application targeting Android 10.
None
- Android
None
N/A
> Update Beacon Readme.txt with Android 10+ prerequisite

- src/Shiny.Beacons/Platforms/iOS/BeaconManager.cs
- src/Shiny.Beacons/Platforms/iOS/PlatformExtensions.cs
Starting iOS 13 uses of CLBeaconRegion for ranging is deprecated. Changed to the new api using CLBeaconIdentityConstraint
https://developer.apple.com/documentation/corelocation/cllocationmanager/3240607-startrangingbeacons
NA
None
- iOS
None
I am not sure how to test it yet.
> iOS 13 uses of CLBeaconRegion for ranging is deprecated.

- src/Shiny.Integrations.Sqlite/SqliteCache.cs
Now GetAsync call from SqliteCache returns default value if object not found
#326 
Changing GetAsync to FindAsync in SqliteCache
- All
Works as expected
Get an object from sqlite cache wich was not yet set
> Getting default value for not yet cached item from SQLite

- src/Shiny.Core/Caching/RepositoryCache.cs
- src/Shiny.Core/Caching/ServiceCollectionExtensions.cs
We check if object is of T type or deserialize it before returning the value from RepositoryCache.Get< T >(key)
fixes #330 
RepositoryCache.Get< T >(key) and its service collection registration
- All
Works like expected
Described in the issue
> #330 fix: No more exception getting item from repository cache

- src/Shiny.Notifications/readme.txt
fixes ReadMe for Shiny.Notifications. The ReadMe currently has some old/invalid references for how to setup Android.
n/a
None
- Android
None
n/a
> fix android docs

- src/Shiny.BluetoothLE/Platforms/Android/AdvertisementData.cs
Bugfix: Crash when a BLE device does not send any ManufacturerSpecificData
I have check the documentation and the API getManufacturerSpecificData must return an array.
My reproduction case was with an empty array. Looking at some other usages of the api on github, I have often see code checking also for null and I have also added a check on it. The method can return null if given a manufacturerId, so I suspect it could also be the case when having no argument.
Official doc : https://developer.android.com/reference/android/bluetooth/le/ScanRecord#getManufacturerSpecificData()
Another app checking for null and empty : https://github.com/angelkjos/BLEBeaconScanner/blob/1ef27ba38f9006f97d8eddfc4db39788880fb4e3/app/src/main/java/com/angelkjoseski/blebeacon/IBeaconResult.java#L28
A native …
> Bugfix: Crash when BLE device does not send any ManufacturerSpecificData

- src/Shiny.BluetoothLE.Abstractions/Extensions_Characteristics.cs
- src/Shiny.BluetoothLE.Abstractions/Feature_Transactions.cs
Fix for BlobWrite when getting near end of buffer to adjust size, otherwise garbage is transmitted after the users data.
- fixes #
None
- All
None
Write data larger then MTU size (e.g. when MTU is 20 bytes, write 63 bytes).
Tested on Android
> Fix for BlobWrite*

- src/Shiny.Notifications/Platforms/Android/NotificationManager.cs
- src/Shiny.Notifications/Platforms/Android/PlatformExtensions.cs
Two changes to Android NotificationManager in Shiny.Notification:
- Generate and use custom sound URI of the form *android.resource://<PKG_NAME>/raw/<RES_NAME>* (e.g. *android.resource://com.shiny.sample/raw/notification*) that allows Android to access the Apps' sound resource (see issue description).
- Call SetSound() with custom sound **before** notification channel is created
NOTE: currently this also sets the vibration mode but I think thats OK
Note that custom sounds on Android 8 and above are only set properly
when the notification channel is created. Changing the sound later
in the Notification will have no effect until the App is re-installed (uninstalled and the installed again).
There might be other workaround too which I don't know of.
- fixes #461 
None
- Android
None
* Tested …
> Fix custom sounds in Shiny.Notification on Android, see issue #461

- samples/Samples/App.xaml.cs
- samples/Samples/SampleStartup.cs
This updates the Sample app to properly link the Prism Container and allow Shiny to populate the DryIoc base container.
none
None
- All
None
None... run the app???
> Simplify container registration with Prism

- src/Shiny.Generators/AndroidActivitySourceGenerator.cs
- src/Shiny.Generators/iOSAppDelegateSourceGenerator.cs
Fixes Generator output. This fixes a few issues actually...
- Multiple lines on a single line making it harder to read
- Adds call to base.OnCreate
- Adds init on iOS for Xamarin.Forms.FormsMaterial
- fixes #564
None
- iOS
- Android
None
On Android add a Splash Activity like you see in the Prism.Forms samples / template. If the app launches when using the generators then it is generating correctly.
> Generator Fixes

- src/Shiny/targets/shiny.targets
Fixes invalid parameter name... the parameter _RefitMSBuildMinVersion does not exist and therefore the Target encounters a parsing error breaking the build.
- hot fix
None
- All
None
Build an app
> fix variable name

- src/Shiny.Generators/ShinyApplicationSourceGenerator.cs
- src/Shiny/targets/shiny.props
Updates the ShinyApplicationSourceGenerator to pull the RootNamespace from the Build props.
- none
None
- All
Generates the Application using the RootNamespace property from the project system with fallback to the Assembly name if the RootNamespace property was null for some reason.
> Use Project Root Namespace

- src/Shiny.Core/Stores/ObjectStoreBinder.cs
- tests/Shiny.Tests.Shared/Core/Stores/StoreTests.ObjectBinder.cs
- tests/Shiny.Tests.Shared/Core/Stores/TestBind.cs
For: https://github.com/shinyorg/shiny/issues/740
See: https://stackoverflow.com/a/10461575/2634818
Only returns properties where the getter and setter are publicly accessible. Doesn't bind PropertyChanged on objects without any available properties.
Would be great to see this patch merged to master for v2.3?
> Fix property accessor check in ObjectStoreBinder

- src/Shiny.Net.Http/Platforms/iOS/HttpTransferManager.cs
The upload task needs a valid file url starting with file:// or else the app will crash.
Before the url looks like this:
`/Users/name/Library/Devices/0306F371-E608-42B1-8C1F-D9315835E5C8/Documents/test.png`
After change:
`file:///Users/name/Library/Devices/0306F371-E608-42B1-8C1F-D9315835E5C8/Documents/test.png`
- fixes #782
None
- iOS
None
> Bug fix: App crashes when file doesn't start with file://

- src/Shiny.Net.Http/Platforms/iOS/HttpTransferManager.cs
- src/Shiny.Net.Http/Platforms/iOS/PlatformExtensions.cs
Added content-type to NsUrlRequest because it was using application/octet-stream, which causes an exception in the asp.net backend. It's also different from the Android upload which uses multipart/form-data.
I also noticed that OnComplete was called while the upload failed with an internal exception. (Haven't looked into that issue yet)
- fixes #782 
None
- iOS
None
> Set content-type of iOS file upload

- src/Shiny.Net.Http/Platforms/iOS/PlatformExtensions.cs
Replaced Environment.NewLine with \r\n because the uploads fail when the web service is run on linux.
web api throws exception:
```
2021-12-03T11:35:34.829989553Z       System.IO.InvalidDataException: Line length limit 100 exceeded.
2021-12-03T11:35:34.830004953Z          at Microsoft.AspNetCore.WebUtilities.BufferedReadStream.ReadLineAsync(Int32 lengthLimit, CancellationToken cancellationToken)
2021-12-03T11:35:34.830009953Z          at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
2021-12-03T11:35:34.830013953Z          at Microsoft.AspNetCore.WebUtilities.StreamHelperExtensions.DrainAsync(Stream stream, ArrayPool`1 bytePool, Nullable`1 limit, CancellationToken cancellationToken) …
```
> Bug fix: Environment.NewLine causes file uploads to fail to linux web api

- src/Shiny.Net.Http/Platforms/iOS/HttpTransferManager.cs
Added extra white lines to the file portion of the post request because the boundary ending was incorporated in the saved file, resulting in a corrupt file on the server. Also added a white line at the beginning of the file part because I was missing some data at the beginning of the saved file.
Don't know if this is a linux only issue.
Lastly I changed the boundary Guid to have no hyphens.
- fixes #782 
None
- iOS
None
> Added extra white lines because the file is malformed on the web server side

- src/Shiny.BluetoothLE.Hosting/IPeripheral.cs
- src/Shiny.BluetoothLE.Hosting/Platforms/Android/GattCharacteristic.cs
- src/Shiny.BluetoothLE.Hosting/Platforms/Android/Internals/GattServerContext.cs
- src/Shiny.BluetoothLE.Hosting/Platforms/Android/Internals/MtuChangedEventArgs.cs
- src/Shiny.BluetoothLE.Hosting/Platforms/Android/Peripheral.cs
- src/Shiny.BluetoothLE.Hosting/Platforms/Uwp/Peripheral.cs
- src/Shiny.BluetoothLE.Hosting/Platforms/ios+macos/Peripheral.cs
An integer property has been added to provide the MTU size of the connected peripheral within the Hosting library.
iOS leverages the `CBCentral.MaximumUpdateValueLength` property.
Windows leverages the `GattSession.MaxPduSize` property.
Android was the most complicated to solve. The solution I have gone for on Android is to simply use the Bluetooth LE default MTU size of 20. If the `OnMtuChanged(BluetoothDevice peripheral, int mtu)` method is called within the `GattServerContext`, then the default MTU value that was originally provided will be updated.
Added `Shiny.BluetoothLE.Hosting.IPeripheral.Mtu: int`
- All
None
iOS is the only platform that I have the capability to test on.
To perform the test, I connected one iOS device to another and wrote out the `IPeripheral.Mtu` value when the …
> Retrieve the MTU of a connected central

- src/Shiny.BluetoothLE/Managed/ManagedPeripheral.cs
fixes GetNotificationObservable() 
- fixes KeyNotFoundException thrown on GetNotificationObservable() subscription.
Since the key does not exist, checked above with ContainsKey() the left operand
evaluation ??= before assignment throws a KeyNotFoundException.
None
- All
None
> fixes KeyNotFoundException on left operand evaluation ??=

- src/Shiny.BluetoothLE/Platforms/Apple/AdvertisementData.cs
The purpose of this PR is to update the behavior of Apple devices in regard to how a Manufacturer Data advertisement is handled. Currently, the Apple implementation requires both a Company ID and at least one byte of data in order to return a non-null result. This differs from the Android implementation which only requires Company ID to be present.
> Update Apple AdvertisementData

- src/Shiny.BluetoothLE/Extensions_Async.cs
I have changed the WriteCharacteristicAsync function, because it was not correctly, if you use the overloaded function call 'public static Task<BleCharacteristicResult> WriteCharacteristicAsync(this IPeripheral peripheral, BleCharacteristicInfo info, byte[] data, bool withResponse = true, CancellationToken cancelToken = default, int timeoutMs = 3000)'
I have changed the signature of this function. Please have a quick review. I think your tests have to be adapted.
public static Task<BleCharacteristicResult> WriteCharacteristicAsync(this IPeripheral peripheral, BleCharacteristicInfo info, byte[] data, bool withoutResponse = false, CancellationToken cancelToken = default, int timeoutMs = 3000) changed to
public static Task<BleCharacteristicResult> WriteCharacteristicAsync(this IPeripheral …
> - Fixed Async-Feature for WriteCharacteristicAsync

- src/Shiny.Beacons/Platforms/Android/ShinyBeaconMonitoringService.cs
- src/Shiny.Core/Platforms/Android/ShinyAndroidForegroundService.cs
- src/Shiny.Locations/Platforms/Android/ShinyGpsService.cs
- src/Shiny.Net.Http/Platforms/Android/HttpTransferService.cs
Some time ago I created the bug #1344 that was fixed very quickly (thanks for that!). When I tested it, I noticed that after these changes the foreground service notification didn't appear on older android versions and that because of this the GPS tracking didn't work anymore when the app is in the background.
I finally had the time to look at why this is happening.
I am not an Android expert, but as far as I understand the documentation, the [ServiceCompat](https://developer.android.com/reference/androidx/core/app/ServiceCompat#startForeground(android.app.Service,int,android.app.Notification,int)) class does all the version checks for us. Using it makes the code much simpler and in my tests, it also worked on older Android versions.
I haven't created an issue for this yet, but I can if …
> Use ServiceCompat to start and stop android foreground service

- samples/Sample.Api/Controllers/PushController.cs
- samples/Sample.Maui/Platforms/Android/AndroidManifest.xml
- src/Shiny.Net.Http/Platforms/Android/HttpTransferService.cs
When multiple http transfers get added within a short time, the http transfer loops gets started multiple times in parallel and some files will be uploaded more than once.
The problem is that `this.platform.StartService(typeof(HttpTransferService), true)` in the `HttpTransferManager` only triggers the service start but does not wait until it was fully started. That's why the `OnStart` of the `HttpTransferService` gets called multiple times.
The good thing is that it seems `OnStart` is always called sequentially and therefor a simple check if `IsStarted` is `true` is enough to prevent starting the loop multiple times.
I also fixed two issues in the sample projects to be able to execute it.
NA
None
Android
There is now only one http transfer loop running instead of multiple parallel loops. …
> Prevent multiple parallel transfer loops

- src/Shiny.Notifications/Platforms/Android/ChannelManager.cs
When channels are created in Android, media volume is what is used, instead of using notification volume. Set the usage to AudioUsageKind.Notification so that all of the volumes work the proper way and the correct sounds are presented to the user.
None
None
- Android
None
Create a new channel on Android and make sure that Notification Volume controls the sound, and not Media Volume.
> set the usage when creating notification channels on Android

- src/Shiny.Push/Platforms/Android/PushManager.cs
- Addressed an issue where if the FirebaseApp is initialized before the RequestNativeToken in Android is invoked, the FirebaseApp fails to load.
- This resolves an issue where Google Crashlytics needs FirebaseApp instance in Maui App's onCreate handler either by using `ConfigureLifecycleEvents` in MauiProgram or by implementing `Shiny.Hosting.IAndroidLifecycle.IOnActivityOnCreate`.
- Avoids `FirebaseApp name [DEFAULT] already exists!` error with following StackTrace:
```CSharp
at Java.Interop.JniEnvironment.StaticMethods.CallStaticObjectMethod(JniObjectReference type, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 21452
at …
```
> [Android] Verified if the FirebaseApp is not already running before initialization.

- samples/Sample.Maui/Platforms/Android/AndroidManifest.xml
- src/Shiny.Notifications/Platforms/Android/NotificationManager.cs
Method `Send(Notification notification)` in android implementation of `INotificationManager` was storing shared type of `Notification` in `repository`, now it will store `Android Notification`.
- fixes #1406
None
- Android
Now scheduled notifications should appear for the user on android platform.
Don't know what to say just try to `notificationManager.Send(notification)` on android with `ScheduleDate` with and without this fix.
I recorded also video before and after fix:
https://github.com/shinyorg/shiny/assets/10498621/774a0d56-702c-4da9-af15-6e46276f9300
https://github.com/shinyorg/shiny/assets/10498621/8f7bacea-9123-418e-b15e-69ec711a9aa9
> Fix for sending scheduled local notifications
